version: "3"
services:
  database:
    image: postgres:9.4
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: local
      POSTGRES_DB: people
      POSTGRES_PASSWORD: local
